---
# Validation

- name: "check if rootfs variable provided right"
  fail:
    msg: >-
      rootfs variable should be defined in 'rootfs_create' or 'rootfs_set'!
  when: rootfs is defined

# Tasks

- name: Check if Container exists and store it in variable
  shell: "if pct status {{ vmid }} > /dev/null 2>&1; then echo true; else echo false; fi"
  register: container_exists
  changed_when: false

- name: Check if VM exists with the given vmid
  shell: "if qm status {{ vmid }} > /dev/null 2>&1; then echo true; else echo false; fi"
  register: vm_exists
  when: container_exists.stdout is match("false")
  changed_when: false

- name: "Stop execution if the provided container vmid is taken by a VM"
  fail:
    msg: >-
      The requested vmid is already taken by a VM!
  when: container_exists.stdout is match("false") and vm_exists.stdout is match("true")

- name: Create Container (pct create ...)
  import_tasks: "commands/container/create.yml"
  when: state is undefined and container_exists.stdout is match("false")

- name: Update Container (pct set ...)
  import_tasks: "commands/container/set.yml"
  when: state is undefined and container_exists.stdout is match("true")

- name: Change state of container
  import_tasks: "commands/container_state.yml"
  when: state is defined
