---
# https://pve.proxmox.com/pve-docs/pct.1.html

- name: Fsck CT
  command: >-
    pct fsck {{ vmid }}
    {% if device is defined %}--device {{ device }}{% endif %}
    {% if force is defined %}--force {{ force }}{% endif %}