---
# https://pve.proxmox.com/pve-docs/pct.1.html

- name: Set CT
  command: >-
    pct set {{ vmid }}
    {% if arch is defined %}--arch {{ arch }}{% endif %}
    {% if cmode is defined %}--cmode {{ cmode }}{% endif %}
    {% if console is defined %}--console {{ console }}{% endif %}
    {% if cores is defined %}--cores {{ cores }}{% endif %}
    {% if cpulimit is defined %}--cpulimit {{ cpulimit }}{% endif %}
    {% if cpuunits is defined %}--cpuunits {{ cpuunits }}{% endif %}
    {% if debug is defined %}--debug {{ debug }}{% endif %}
    {% if delete is defined %}--delete "{{ delete }}"{% endif %}
    {% if description is defined %}--description "{{ description }}"{% endif %}
    {% if digest is defined %}--digest "{{ digest }}"{% endif %}
    {% if features is defined %}--features {{ features }}{% endif %}
    {% if hookscript is defined %}--hookscript "{{ hookscript }}"{% endif %}
    {% if hostname is defined %}--hostname "{{ hostname }}"{% endif %}
    {% if lock is defined %}--lock {{ lock }}{% endif %}
    {% if memory is defined %}--memory {{ memory }}{% endif %}
    {% if mp_arr is defined %}{% for mp in mp_arr %}--mp{{ mp.n }} {{ mp.args }} {% endfor %}{% endif%}
    {% if nameserver is defined %}--nameserver "{{ nameserver }}"{% endif %}
    {% if net_arr is defined %}{% for net in net_arr %}--net{{ net.n }} {{ net.args }} {% endfor %}{% endif %}
    {% if onboot is defined %}--onboot {{ onboot }}{% endif %}
    {% if ostype is defined %}--ostype {{ ostype }}{% endif %}
    {% if protection is defined %}--protection {{ protection }}{% endif %}
    {% if revert is defined %}--revert "{{ revert }}"{% endif %}
    {% if rootfs_set is defined %}--rootfs {{ rootfs_set }}{% endif %}
    {% if searchdomain is defined %}--searchdomain "{{ searchdomain }}"{% endif %}
    {% if startup is defined %}--startup {{ startup }}{% endif %}
    {% if swap is defined %}--swap {{ swap }}{% endif %}
    {% if tags is defined %}--tags "{{ tags }}"{% endif %}
    {% if template is defined %}--template {{ template }}{% endif %}
    {% if timezone is defined %}--timezone "{{ timezone }}"{% endif %}
    {% if tty is defined %}--tty {{ tty }}{% endif %}
    {% if unprivileged is defined %}--unprivileged {{ unprivileged }}{% endif %}
    {% if unused_arr is defined %}{% for unused in unused_arr %}--unused{{ unused.n }} {{ unused.args }} {% endfor %}{% endif %}
  changed_when: true