---
# https://pve.proxmox.com/pve-docs/qm.1.html

- name: Importdisk to VM
  command: >-
    qm importdisk {{ vmid }} "{{ source }}" "{{ storage }}"
    {% if format is defined %}--format {{ format }}{% endif %}
  changed_when: true
