

- name: Destroy (pct destroy ...)
  import_tasks: "commands/container/destroy.yml"
  when: container_exists.stdout is match("true")

- name: Already destroyed
  debug:
    msg: Container is already destroyed
  when: container_exists.stdout is match("false")
  changed_when: false